/*
 * File Description:
 * This file defines mock data sources for category (Category) data, used for frontend project development and testing.
 *
 * Main Content:
 * - Imports the category type definition (Category) and the PRODUCTS mock data.
 * - Exports a constant CATEGORIES array, containing multiple category objects. Each category includes name, slug, imageUrl, and a filtered list of products belonging to that category.
 *
 * Notes:
 * - The products field is generated by filtering the PRODUCTS array by category slug.
 * - This file provides mock data and can be replaced with backend API data in actual development.
 */

/*
 * 文件说明：
 * 本文件定义了分类（Category）数据的模拟数据源，供前端项目开发和测试使用。
 *
 * 主要内容：
 * - 导入了分类类型定义（Category）和商品模拟数据（PRODUCTS）。
 * - 导出了一个 CATEGORIES 常量数组，包含多个分类对象。每个分类包含名称、slug、图片地址和属于该分类的商品列表。
 *
 * 注意事项：
 * - products 字段通过过滤 PRODUCTS 数组按分类 slug 生成。
 * - 本文件为模拟数据，实际开发中可替换为后端接口数据。
 */

import { Category } from "../types/category";
import { PRODUCTS } from "./products";

export const CATEGORIES: Category[] = [
    {
        name: "Laptops",
        slug: 'laptops',
        imageUrl: 'https://images.pexels.com/photos/129208/pexels-photo-129208.jpeg',
        products: PRODUCTS.filter(product => product.category && product.category.slug === 'laptops'),
        // check product in PRODUCTS has category, then filter the products by category slug
    },
    {
        name: 'Phones',
        slug: 'phones',
        imageUrl:
            'https://images.pexels.com/photos/40739/mobile-phone-smartphone-tablet-white-40739.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        products: PRODUCTS.filter(product => product.category && product.category.slug === 'phones'),
    },
    {
        name: 'Gaming',
        slug: 'gaming',
        imageUrl:
          'https://images.pexels.com/photos/275033/pexels-photo-275033.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        products: PRODUCTS.filter(product => product.category && product.category.slug === 'gaming'),
      },
      {
        name: 'Accessories',
        slug: 'accessories',
        imageUrl:
          'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        products: PRODUCTS.filter(
          product => product.category && product.category.slug === 'accessories'
        ),
      },
]